### PR TITLE
adding boilerplate ml5 example to be referenced from Getting Started …

### PR DESCRIPTION
**Pull request by shiffman**
## → Description 📝

Since the Getting Started page references a "boilerplate" example (with a link to the web editor) I thought maybe it might be good to include it here so that it goes to the ml5 web editor account? (Currently the link is to: https://editor.p5js.org/joeyklee/sketches/5VbXAWaV6)

## → Screenshots 🖼

Screen Shot 2019-05-23 at 1 24 00 PM

### CODE REVIEW

**Comment by joeyklee** [comment]
@shiffman - ah yes. This was actually on purpose. The reason being, our current ml5-fetch-examples script will automatically delete this each time until we add a folder in our examples that has this boilerplate setup inside. This should be an easy fix, but for now I won't merge until we've updated this. Cool? Thank you!

**Comment by shiffman** [comment]
Ah, of course! Are we also going to have an issue with the sketch URL generates as something different each time? (I suppose this applies to all links to p5 web editor examples?)

**Comment by joeyklee** [comment]
@shiffman - We won't have an issue with that since Cassie implemented a really nice feature that creates a slug for the url ending based on the name of the sketch :)

**Comment by joeyklee** [comment]
Closing this one up now in favor of: https://github.com/ml5js/ml5-boilerplate 
Thanks @shiffman !

**Pull request closed without merging**
