### PR TITLE
Drag and drog vanilla JS example

### PR DESCRIPTION
**Pull request by shiffman**
This is a vanilla JavaScript example that allows the user to drag and drop a new image onto the HTML element and have it classified. I'm not sure if we want/need this to be an example in the repo itself so we don't necessarily need to merge. I am working on it with @matamalaortiz for the ml5 homepage. Some notes:

1) @yining1023 do you have suggestions for the best way for us to integrate this on the homepage with React? You can see the current site in this fork: https://github.com/matamalaortiz/ml5-website

2) I'm not sure why but I'm having trouble calling `classifyImage()` in the `onloadend` callback. It seems to work fine if I just use a little `setTimeout()` but that's not a great solution.

3) For the site, we'll want some error handling. What if the file is not an image? etc.

4) We'll also want to be careful about styling, constraining the image to certain dimensions as well as adding classes to style the drag/drop area depending on the event: `['dragenter', 'dragover', 'dragleave', 'drop']`. (Note the code refers to a made up `highlight` class).

### CODE REVIEW

**Comment by cvalenzuela** [comment]
I'll investigate the `onloadend` issue

**Comment by yining1023** [comment]
I think we can create a React component with drag and drop functionality and render it on `website/pages/en/index.js`. We probably need to port the view part of the things from vanilla js to React, but everything else could be the same.

I'd love to port this example to ml5-website. I can make a PR to https://github.com/matamalaortiz/ml5-website.

Totally agree on note 3. and 4.!

**Comment by yining1023** [comment]
Thank you, @matamalaortiz! I just submitted a PR to your repo.

**Comment by shiffman** [comment]
I'm going to close this, we can revisit making this an actual ml5 example at some point. But for the moment this code was designed just to work for the ml5 homepage.

**Comment by shiffman** [comment]
Follow progress here: https://github.com/matamalaortiz/ml5-website/pull/3

**Pull request closed without merging**
