### PR TITLE
Object detector examples update

### PR DESCRIPTION
**Pull request by tirtawr**
Dear ml5 community, 

I'm making a Pull Request(PR). Please see the details below.

**A good PR 🌟**

**A great PR 🌟🌟**

**The best PR 🌟🌟🌟**

### CODE REVIEW

**Review by loaiabdalslam — APPROVED** [review]

**Review by loaiabdalslam — CHANGES_REQUESTED** [review]
Please Make a small description about your steps why we changed all files meta links to 
`localhost:8080/ml5 `

**Comment by shiffman** [comment]
Woohoo, excited about this, thank you @tirtawr! I think this pull request needs to be made to `development` rather than release!

**Comment by tirtawr** [comment]
@shiffman oops, my bad. I've updated the target branch.

@loaiabdalslam Hmm, yeah I'm not sure about this. I was just following the examples that were already there 😅. Maybe @joeyklee knows more about this? It might be because currently for these specific examples we're using an unreleased version of ml5 that's still in the development branch.

**Comment by shiffman** [comment]
@tirtawr that's correct! In the `development` branch, the ml5 library points to a locally built file (which assumes you are building your own dev version of the library), the `release` examples point to the actual release! @loaiabdalslam

**Comment by joeyklee** [comment]
Many thanks @tirtawr ! Merged! 🙏

**Pull request merged**
