### PR TITLE
reorganize p5js folder

### PR DESCRIPTION
**Pull request by montoyamoraga**
I reorganized the p5.js examples to live in folders according to the model they are using, so it's less cluttered, to address #50.

### CODE REVIEW

**Comment by cvalenzuela** [comment]
great! thanks @montoyamoraga!

We thought of grouping them into input type, but I think this works well too. @shiffman?

**Comment by shiffman** [comment]
oh, i like this too!

**Comment by cvalenzuela** [comment]
Before merging this, we need to also update the website references to the examples.
For example, in https://ml5js.org/docs/image-classification-example:
Here:
screen shot 2018-08-08 at 12 04 10
And here
screen shot 2018-08-08 at 12 04 25

@montoyamoraga 😄 ?

**Comment by montoyamoraga** [comment]
@cvalenzuela okie, done here
[https://github.com/ml5js/ml5-website/pull/78](https://github.com/ml5js/ml5-website/pull/78)

**Comment by cvalenzuela** [comment]
thanks @montoyamoraga! we should also update the links in the API pages

**Comment by montoyamoraga** [comment]
@cvalenzuela done!

**Comment by cvalenzuela** [comment]
great, thanks @montoyamoraga!

**Pull request merged**
