### PR TITLE
GAN example cleanup

### PR DESCRIPTION
**Pull request by shiffman**
## → Description 📝

Just a little clean-up of the comments and also I added hiding the button until the model is loaded since it takes a little while and hitting the button beforehand produces an error. @viztopia, does `ml5.DCGAN()` support `preload()`?

### CODE REVIEW

**Comment by joeyklee** [comment]
I will add these to development as well! Thanks Dan!

**Comment by viztopia** [comment]
@shiffman I just checked the src/index.js, and DCGAN hasn't been put into withPreload. Should I go ahead and add a PR for it?

**Comment by shiffman** [comment]
@viztopia thanks! Yes, I think it's nice for us to support `preload()` as much as possible in ml5!

**Comment by joeyklee** [comment]
Hi @shiffman @viztopia:

I took a quick look at this and it seems there's something about the way DCGAN is structured that doesn't allow for it is support preload out of the box. Basically the model doesn't finish loading before moving on to setup(). 

```javascript
// Copyright (c) 2018 ml5
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

/* ===
ml5 Example
DCGAN example
=== */

let dcgan;
let outputCanvas;
let button;

function preload(){
  // Load the model
  // There can be multiple pre-trained models (e.g. cats, flowers, etc.), just like SketchRNN
  dcgan = ml5.DCGAN('face');

}

function setup() {
  createCanvas(400, 400);
  // generate on page load
  console.log(dcgan)
  generate();
  // Button to generate an image
  button = createButton('generate');
  button.mousePressed(generate);

}

function generate() {
  // Generate function receives a callback for when image is ready
  dcgan.generate(displayImage);
  console.log(dcgan)
}

function displayImage(err, result) {
  if (err) {
    console.log(err);
    return;
  }
  image(result.image, 0, 0, 400, 400);
}

```


```
TypeError: "_this.model is null"
    y index.js:74
    tidy tf-core.esm.js:17
    scopedRun tf-core.esm.js:17
    tidy tf-core.esm.js:17
    Fe tf-core.esm.js:17
    _callee3$ index.js:71
    tryCatch runtime.js:62
    invoke runtime.js:296
    method runtime.js:114
    step asyncToGenerator.js:17
    default asyncToGenerator.js:35
    Promise es6.promise.js:177
    default asyncToGenerator.js:14
    compute ml5.js:50984
    _callee4$ index.js:88
    tryCatch runtime.js:62
    invoke runtime.js:296
    method runtime.js:114
    step asyncToGenerator.js:17
    default asyncToGenerator.js:35
    Promise es6.promise.js:177
    default asyncToGenerator.js:14
    generateInternal ml5.js:51066
    _callee2$ index.js:62
    tryCatch runtime.js:62
    invoke runtime.js:296
    method runtime.js:114
    step asyncToGenerator.js:17
    default asyncToGenerator.js:35
    Promise es6.promise.js:177
    default asyncToGenerator.js:14
    generate ml5.js:50944
    generate sketch.js:35
    setup sketch.js:26
    _setup p5.min.js:3
    _runIfPreloadsAreDone p5.min.js:3
    _start p5.min.js:3
    m p5.min.js:3
    n p5.min.js:3
```

**Comment by joeyklee** [comment]
In chrome:

```
DCGANBase {modelCache: {…}, modelName: "face", model: null, ready: Promise}
sketch.js:36 DCGANBase {modelCache: {…}, modelName: "face", model: null, ready: Promise}
sketch.js:41 TypeError: Cannot read property 'predict' of null
    at index.js:74
    at tf-core.esm.js:17
    at t.scopedRun (tf-core.esm.js:17)
    at t.tidy (tf-core.esm.js:17)
    at Object.Fe (tf-core.esm.js:17)
    at DCGANBase._callee3$ (index.js:71)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:296)
    at Generator.prototype.<computed> [as next] (runtime.js:114)
    at step (asyncToGenerator.js:17)
index.js:74 Uncaught (in promise) TypeError: Cannot read property 'predict' of null
    at index.js:74
    at tf-core.esm.js:17
    at t.scopedRun (tf-core.esm.js:17)
    at t.tidy (tf-core.esm.js:17)
    at Object.Fe (tf-core.esm.js:17)
    at DCGANBase._callee3$ (index.js:71)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:296)
    at Generator.prototype.<computed> [as next] (runtime.js:114)
    at step (asyncToGenerator.js:17)
```

**Comment by viztopia** [comment]
Hi @joeyklee ,

I just moved DCGAN into WithPreload, recompile ml5.js, and moved:
`dcgan = ml5.DCGAN('face', modelReady); `
under preload(), and it worked. Is it because of the callback?

Here's the complete example code:

```
/* ===
ml5 Example
DCGAN example
=== */

let dcgan;
let outputCanvas;
let button;

function preload(){
  dcgan = ml5.DCGAN('face', modelReady);
  console.log("preload!");
}

function setup() {
  createCanvas(400, 400);
  // Load the model
  // There can be multiple pre-trained models (e.g. cats, flowers, etc.), just like SketchRNN
  // dcgan = ml5.DCGAN('face', modelReady);

  // Button to generate an image
  button = createButton('generate');
  button.mousePressed(generate);
  // Hiding button until model is ready
  button.hide();
}

function generate() {
  // Generate function receives a callback for when image is ready
  dcgan.generate(displayImage);
}

function displayImage(err, result) {
  if (err) {
    console.log(err);
    return;
  }
  image(result.image, 0, 0, 400, 400);
}

function modelReady() {
  console.log('model is ready');
  button.show();
  generate();
}
```

And here's my modified ml5-library/src/index.js:

```// Copyright (c) 2018 ml5
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

import * as tf from '@tensorflow/tfjs';
import pitchDetection from './PitchDetection/';
import imageClassifier from './ImageClassifier/';
import soundClassifier from './SoundClassifier/';
import KNNClassifier from './KNNClassifier/';
import featureExtractor from './FeatureExtractor/';
import word2vec from './Word2vec/';
import YOLO from './YOLO';
import poseNet from './PoseNet';
import * as imageUtils from './utils/imageUtilities';
import styleTransfer from './StyleTransfer/';
import charRNN from './CharRNN/';
import pix2pix from './Pix2pix/';
import sketchRNN from './SketchRNN';
import uNet from './UNET';
import CVAE from './CVAE';
import DCGAN from './DCGAN';
import preloadRegister from './utils/p5PreloadHelper';
import { version } from '../package.json';
import sentiment from './Sentiment';

const withPreload = {
  charRNN,
  CVAE,
  DCGAN,
  featureExtractor,
  imageClassifier,
  soundClassifier,
  pitchDetection,
  pix2pix,
  poseNet,
  sketchRNN,
  styleTransfer,
  word2vec,
  YOLO,
  uNet,
};

module.exports = Object.assign({}, preloadRegister(withPreload), {
  KNNClassifier,
  ...imageUtils,
  // DCGAN,
  tf,
  version,
  sentiment,
});
```

**Comment by joeyklee** [comment]
@viztopia I'm afraid it's not as straightforward as this, but it is a start. Technically what preload() should do is remove the need for the callback function inside the model instantiation. 

Your modification won't successfully run `generate()` in `setup()`  -- an error saying "this.model.predict()" is not a function will be thrown. I suspect that tf.loadLayersModel() doesn't get finished loading and as a result, you don't have a model loaded yet and therefore no way to run your prediction. 

I'm also working on trying to get this to work, but it turns out preload isn't waiting for things to load before continuing. Maybe @WenheLI or @NHibiki might have an idea? 

On an unrelated but related note:
I've refactored DCGAN a bit here:
https://github.com/ml5js/ml5-library/pull/397

And added and example here:
https://github.com/ml5js/ml5-examples/pull/151

The ^^ above will allow for easier changing of pre-trained models but I suspect there's some things we might want to clean up/set some presets.

**Comment by joeyklee** [comment]
@viztopia - this should be working. Please give this a test if you can: https://github.com/ml5js/ml5-library/pull/398

**Pull request merged**
