### PR TITLE
[Universal sentence encoder] Adds example for Universal Sentence Encoder

### PR DESCRIPTION
**Pull request by joeyklee**
Dear ml5 community, 

I'm making a Pull Request(PR). Please see the details below.

**A good PR 🌟**

* development

* adds the Universal Sentence encoder: https://github.com/tensorflow/tfjs-models/tree/master/universal-sentence-encoder 
* Related to: https://github.com/ml5js/ml5-library/issues/197

### CODE REVIEW

**Comment by bomanimc** [comment]
@joeyklee is this a PR you'd be interested in merging here, or would you prefer to open this PR on ml5-library after the merge of the libraries?

**Comment by joeyklee** [comment]
Hi @bomanimc!

For simplicity, let's do it this way:

1. Re: ml5js/ml5-examples#262 (comment) - Let's merge the PR for this feature and the PR for the example now.
2.  We can refine and update once the m5-examples and library merge is complete.
3. We can leave it undocumented until we feel it is ready for more public usage and once we have some more examples showcasing how it works, but for simplicity of devOps, I think it is ok to merge.

**Comment by bomanimc** [comment]
@joeyklee you already know this of course, but adding a note here just in case someone comes across this in the future!

We're archiving this repository and moving its contents into the core [ml5-library](https://github.com/ml5js/ml5-library) repository (more context on [issue #809](https://github.com/ml5js/ml5-library/issues/809) and [pull request #831](https://github.com/ml5js/ml5-library/pull/831)). We appreciate your contributions and would love it if you'd consider reopening this pull request on the [ml5-library](https://github.com/ml5js/ml5-library) repo! Thanks!

**Comment by joeyklee** [comment]
Thank you! Will make a new PR in the ml5-library! 🙏

**Pull request closed without merging**
