### PR TITLE
added interactive regression example

### PR DESCRIPTION
**Pull request by LudwigStumpp**
Dear ml5 community, 

I'm making a Pull Request(PR). Please see the details below.

### → Step 1:  Which branch are you submitting to? 🌲
`development` to add an example for Regression.

### → Step 2: Describe your Pull Request 📝
I am submitting a new interactive example for Regression using the `NeuralNetwork` class.

Previously there were some problems with it, described at https://github.com/ml5js/ml5-library/issues/721. Basically, the issue was that not all data points were taken into account (since the `validationSplit` parameter of the `NeuralNetwork` training option was permanently set to 0.1).

But since this issue is now closed and changes were merged to the `development` branch (see https://github.com/ml5js/ml5-library/commit/f749d4e00b4b87b76902fd4e8a837fd50398e827; `src/NeuralNetwork/NeuralNetwork.js`; `line 108`) the example now works as expected.

The idea behind this example is that one can add multiple data points to use regression to fit a line. The already present example of `NeuralNetwork_Simple_Regression` does not have the feature to add points interactively + to change some core model parameters. This is why I wanted to share this example.

One can add data points and modify:
- `learningRate`
- `hiddenUnits`
- `batchSize`
- `epochs`

and see the changes.

I would not be upset if you decide not to add this example, since it might be a little bit redundant compared to `NeuralNetwork_Simple_Regression`.

image

### CODE REVIEW

**Comment by joeyklee** [comment]
@LudwigStumpp - Apologies for the super late reply here! Wow this example is awesome and very cool to be able to use these inputs! 

@shiffman @bomanimc - I've been thinking maybe there's a separate spot on our website we might be able to highlight these kinds of projects that are slightly more advanced but still very helpful references for teaching? Feels like it might also be a consideration for the the upcoming work of @AndreasRef ?

**Comment by shiffman** [comment]
@joeyklee yes, I agree! Thanks for this wonderful contributions @LudwigStumpp! I never loved the term "demos" but something along that line could make sense?

**Comment by LudwigStumpp** [comment]
@joeyklee  @shiffman  thank you! The term "demo" does indeed make sense in my opinion.

**Comment by joeyklee** [comment]
Looping in @bomanimc into this thread as I think this also relates to the work thinking about future devOps processes and where we might include / separate out "demos" vs. "examples". 

Also related to Andreas Refsgaard and Emily's Fellowship!

**Comment by bomanimc** [comment]
I think that having a demos section makes sense as well! I'd be happy to help with adding some changes to the ml5 examples index site to make those changes apparent. 

It may make sense to merge these changes in as examples for now, and then move them into a demo section later. We'll likely be archiving this repository soon as a part of the changes we're making to https://github.com/ml5js/ml5-library/pull/831. If that happens before these changes are merge, please feel free to reopen on https://github.com/ml5js/ml5-library!

**Comment by bomanimc** [comment]
Hey @LudwigStumpp! We're archiving this repository and moving its contents into the core [ml5-library](https://github.com/ml5js/ml5-library) repository (more context on [issue #809](https://github.com/ml5js/ml5-library/issues/809) and [pull request #831](https://github.com/ml5js/ml5-library/pull/831)). We appreciate your contributions and would love it if you'd consider reopening this pull request on the [ml5-library](https://github.com/ml5js/ml5-library) repo! Thanks!

**Comment by LudwigStumpp** [comment]
Done. This can be closed now, I guess.

**Pull request closed without merging**
