### PR TITLE
Updating Titanic Example

### PR DESCRIPTION
**Pull request by shiffman**
## → Description 📝

I am working on updating the Titanic example to follow [the "cleaned" data](https://docs.google.com/spreadsheets/d/1UKmuTgY8qWnZ-jQm9NBL0HGwlJS4e4VQTgNXTtluTCw/edit#gid=1774164161) from @lydiajessup. The changes are:

* adding "fare class*
* using strings as input labels
* passing in an object to `predict()`.

At the moment, I'm stuck on training with this error. Investigating... 

Screen Shot 2019-09-24 at 11 27 27 AM

### CODE REVIEW

**Comment by shiffman** [comment]
Never mind hadn't pulled the latest! Training is working so far as I can tell. Testing prediction next.

Screen Shot 2019-09-24 at 11 32 10 AM

**Comment by joeyklee** [comment]
@shiffman - currently inputs need to be an array rather than json object! That might do it!

**Comment by shiffman** [comment]
Here are the ways I imagine passing in the inputs. The first (array) I am getting an error. The second (object) we do not yet support but could consider.

## Passing in array:

```javascript
let inputs = ['first', 'female', 32, 100];
neuralNetwork.classify(inputs, gotResults);
```
Screen Shot 2019-09-24 at 11 38 10 AM

--------

## Passing in Object

```javascript
  let inputs = {
    age: 32,
    fare: 100,
    fare_class: 'first',
    sex: 'female'
  };
  neuralNetwork.classify(inputs, gotResults);
```

**Comment by joeyklee** [comment]
@shiffman - Noted! At the moment, we can only pass in an array that matches the normalized data. 

So in this instance:

`[32, 100, 'first', 'female']` ==> `[0.32, 0.7, 0,0,1, 0, 1]`

This is due to the oneHot encoding. We may have to do some refactoring to handle this in a manageable way. TBD!

**Comment by shiffman** [comment]
Indeed I can confirm that works! The example now manually encodes the inputs with notes about possible other ways of handling it.

```javascript
function classify() {
  let age = parseInt(select('#age').value());
  let fare = parseInt(select('#fare').value());
  let fare_class = select('#fare_class').value();
  let sex = select('#sex').value();

  // TODO: Support inputs same as data formats: ['fare_class', 'sex', 'age', 'fare'],
  // TODO: Autonormalize or more likely include extra step of normalizaton
  // let inputs = [fare_class, sex, age, fare,];

  // Evenutally also support objects
  // let inputs = {
  //   age: 32,
  //   fare: 100,
  //   fare_class: 'first',
  //   sex: 'female'
  // };

  // For testing now
  let inputs = [0.32, 0.7, 0, 0, 1, 0, 1];
  neuralNetwork.classify(inputs, gotResults);
```

Screen Shot 2019-09-24 at 1 46 23 PM

**Comment by lydiajessup** [comment]
AMAZING!!!! This is so beautiful to see!!!

**Comment by joeyklee** [comment]
WIP: 

Screen Shot 2019-09-24 at 23 10 38

**Comment by shiffman** [comment]
Oh, I seriously ❤️the naming of the property `legend`. This is a great way of handling it (better than some of the futzing I was just doing. . Don't forget to 💤!)

**Pull request merged**
