### PR TITLE
DCGAN Latent Vector Examples

### PR DESCRIPTION
**Pull request by shiffman**
## → Description 📝

- I reviewed #175 and had some ideas for latent vector examples. 

## → Idea 1: Random Walk?

I think this is a simpler way to demonstrate how to move about the latent space rather than continuously picking new points and interpolating?

## → Idea 2: Slider?

I love the idea of using `lerp()` so maybe a nice demonstration of the idea is to have a slider that allows the user to play with interpolating between two vectors. I am not able to produce smooth results (with this technique or the previous one, is this perhaps just due to the example model being fuzzy?)

### CODE REVIEW

**Comment by shiffman** [comment]
Tagging @genekogan for thoughts on how these concepts are traditionally demonstrated in the context of his courses / materials?

**Review by genekogan — APPROVED** [review]
I think these are great. Only thing I would think it might be better to use gaussian noise in RandomWalk instead of Brownian motion (`vector[i] += random(-0.01, 0.01);`) as the later may not get very far. But that's a pretty minor nitpick.

Another thing I think would be nice to have is a labeled DCGAN (like one trained on MNIST) so that in addition to the latent vector, you give it labels as well (and so you can do interpolations between digit X and digit Y, for example). Class-conditional generative models (like BigGAN for example) are great because they are more intuitive for understanding how features can be added and subtracted like DNA. That's true for latents as well, but since the latents seem random/unordered, it's not as easy to show that as it is "give me 0.5 * dog + 0.5 * cat".

**Comment by joeyklee** [comment]
@shiffman - Thanks for these! The advantage of the random walk is that it is simple, but @genekogan is right in that maybe the walker doesn't get so far. We can tune this as we see fit.

I'd love to explore at some point @genekogan mentioned above with the class conditional models. That would be really nice for teaching the concept of latent space. _adds to dream list_ ;)

**Comment by shiffman** [comment]
I played around with some new techniques for this render created with Runyway. Remind me to make an example that demonstrates this methodology involving perlin noise in the future!

https://twitter.com/shiffman/status/1156310575137329154

**Pull request merged**
