### PR TITLE
work on neural network color classifier

### PR DESCRIPTION
**Pull request by shiffman**
## → Description 📝

These are relatively unimportant changes but putting this here as it's the code I'm testing with https://github.com/ml5js/ml5-library/pull/574.

### CODE REVIEW

**Comment by shiffman** [comment]
This example is (mostly) ready! These are the two remaining items to be addressed in https://github.com/ml5js/ml5-library/pull/485 before merging.

* [x] Support for `whileTraining(epoch, loss)` callback. This allows the ml5 user to design their training report other than tf-vis.
* [x] Support for returning labels in callback of `predict()` method. At the moment, I am doing this manually in the code, but not getting the correct labels. I imagine I have them in the wrong order.

**Comment by joeyklee** [comment]
@shiffman - I can start working on the `whileTraining()` and will move forward from there. Thanks!

**Comment by joeyklee** [comment]
@shiffman  - for callback support `whileTraining`: https://github.com/ml5js/ml5-library/pull/577 Will merge when the tests pass :) -- done!

**Comment by joeyklee** [comment]
@shiffman - just writing a note for our reference on what needs to be added to make the `predict()` function work in the way we'd like:

```
  async predictInternal(sample) {
    
    // TODO: handle the input sample
    // either an array of values in order of the inputs
    // OR an JSON object of key/values
    // We need to normalize the inputs -- need to store the min/max values
    // for each input/output to use them here AND for unnormalizing for outputs


    const xs = tf.tensor(sample, [1, sample.length]);
    const ys = this.model.predict(xs);

    ...


```

**Pull request merged**
