### PR TITLE
Refactors examples to match diy-nn-refactor branch

### PR DESCRIPTION
**Pull request by joeyklee**
related to: https://github.com/ml5js/ml5-library/pull/591

### CODE REVIEW

**Comment by joeyklee** [comment]
@shiffman - Hi! I've merged in your https://github.com/ml5js/ml5-examples/pull/194 into this PR and updated all the examples. 


Re: custom normalization: I've added an experimetnal feature to add in a normalizationOptions object that allows you to run the pixelBrain example! 

I think this PR https://github.com/ml5js/ml5-library/pull/591 also improves the classification results from the Titanic example as well. I could be wrong, but I think it is working!

Maybe try to run https://github.com/ml5js/ml5-library/pull/591 in tandem with this PR to test?

**Comment by shiffman** [comment]
Thanks for this @joeyklee, amazing!

Focusing on the "interactive" data examples at the moment, but just noting that I am getting an error in the titanic example with this branch and building the library from https://github.com/ml5js/ml5-library/pull/591.

Screen Shot 2019-10-02 at 8 53 58 AM

**Comment by shiffman** [comment]
Ah, oops, actually this is an error for all examples that don't include `normalizationOptions`. Tested by adding the `normalizationOptions: {}`. I pushed a quick fix in https://github.com/ml5js/ml5-library/pull/591/commits/88af7ea8917b6c1258c819509b4671cd866b29f6.

**Comment by joeyklee** [comment]
Merging this in now! Thanks @shiffman for all the feedback and hard work!

**Pull request merged**
