### PR TITLE
Posenet Classifier

### PR DESCRIPTION
**Pull request by shiffman**
## → Description 📝

New example demonstrating classifying a pose with `ml5.poseNet()` and `ml5.neuralNetwork()`. Designed to work with https://github.com/ml5js/ml5-library/pull/596.

## → Screenshots 🖼

posenet320

### CODE REVIEW

**Comment by joeyklee** [comment]
I literally just `lol'd` watching this gif. Amazing 😂

**Comment by joeyklee** [comment]
@shiffman one thing we should note is that right now the posenet version we're using isn't as accurate as the previous version due to the way that posenet is handling image resizing. @oveddan has addressed this in the posenet model https://github.com/tensorflow/tfjs-models/pull/296 but I think we're still waiting for it to be merged in. If you notice any inaccuracies, it is likely due to the image resizing issue.

**Comment by oveddan** [comment]
@joeyklee @shiffman that PR is super close to being merged so we should be good soon!

**Comment by joeyklee** [comment]
@oveddan - Thanks so much! We are so lucky to have you in the mix! 🙏

**Pull request merged**
