### PR TITLE
DIY Neural Network mouseXY classification example

### PR DESCRIPTION
**Pull request by shiffman**
## → Description 📝

This is an attempt at making a new example that classifies `x,y` positions (added by mouse clicks) according to two labels: `A` / `B`. I think I'm very close, but current status is that it hangs on `train()` and only returns `A`.

## → Screenshots 🖼

Screen Shot 2019-10-02 at 8 48 51 PM

### CODE REVIEW

**Comment by shiffman** [comment]
ooops, I went branch crazy, this should be merged to `nn-examples-cleanup`. I'll sort out.

**Comment by shiffman** [comment]
This should be good now, multiple commits above but changes reflect new example only.

**Comment by joeyklee** [comment]
@shiffman - there were 2 errors: 
1. outputs should be 2 - "A" and "B"
2. `.predict()` should be `.classify()` 

These are fixed in https://github.com/ml5js/ml5-examples/pull/199/commits/814fd9ede5e96e4f5c1ac0817af4fa14395a0938

Feel free to merge when ready!

**Comment by shiffman** [comment]
Ah, yes, of course that makes sense!! 

This is a little tricky b/c with, say, the titanic dataset there was only a single "column" name listed:

```javascript
  const options = {
    outputs: ['survived'],
    task: 'classification'
  }
```

So maybe this is more like . . .

```javascript
  // Create the model
  const options = {
    inputs: 2,
    labels: ['A', 'B'],
    task: 'classification'
  }
```

Also, as an aside, It would be interesting to consider how it might work to create the model after the dataset is collected. For example a la teachable machines where a user is entering in label names. This would be an argument for a separate `ml5.data()` function where you prepare the dataset and then create the model. But one thing at a time!

**Comment by joeyklee** [comment]
> Ah, yes, of course that makes sense!!
> 
> This is a little tricky b/c with, say, the titanic dataset there was only a single "column" name listed:
> 
> ```js
>   const options = {
>     outputs: ['survived'],
>     task: 'classification'
>   }
> ```
> 
> So maybe this is more like . . .
> 
> ```js
>   // Create the model
>   const options = {
>     inputs: 2,
>     labels: ['A', 'B'],
>     task: 'classification'
>   }
> ```
> 
> Also, as an aside, It would be interesting to consider how it might work to create the model after the dataset is collected. For example a la teachable machines where a user is entering in label names. This would be an argument for a separate `ml5.data()` function where you prepare the dataset and then create the model. But one thing at a time!

+ hmm yes this is interesting. I think for now it is ok if you have to put in the number of inputs/outputs if you're creating a "blank" neural net. It means that you have to be explicit about the number of "inputs" and "outputs" which I think matches some of your examples like with your flappy bird example. The label names are then retrieved from the data after being fed in with `.addData()`. 

+ With the Titanic example or any of the examples where data are loaded in on object instantiation, I think it works that the data class figures out the nature of the data. I do think it is good to support explicitly adding in the output names in the constructor to make it clearer though! I'll add to the list of todos.

**Comment by joeyklee** [comment]
@shiffman - I will merge this in for now and work on allowing people to specify the `['a','b']` labels for the outputs in classification. Thank you!

**Comment by shiffman** [comment]
Yes, thank you, your comments are super helpful and clarifying! Excited to keep pushing this new feature forward!

**Pull request merged**
